### ISSUE TITLE
Explicitly state the schema mode

### ISSUE THREAD

**Issue by tokee** [kb-dk/solr-and-snippets#90]
There is a `schema.xml`-file, but Solr uses managed schema per default. Those are conflicting signals that Solr complains about during startup. If the project uses managed schema, the `schema.xml` should be removed. If it uses static schema, `sorlconfig.xml` should state it with
```
https://lucene.apache.org/solr/guide/7_7/schema-factory-definition-in-solrconfig.html
```
(I recomment using static schemas is the setups at the Royal Danish Library as it makes it easy to have a consistent schema under version control and across installations)

See https://lucene.apache.org/solr/guide/7_7/schema-factory-definition-in-solrconfig.html for details.

**Comment by siglun** [comment]
Thanks Tokee. Haven't noticed you comment until now, sorry. I've seen these complaints in the logs, but haven't had the time to understand what it really means...
